dir: "{{ cache }}/nodebrew"

commands:
  - brew install nodebrew
  - nodebrew setup_dirs
  - nodebrew install-binary v6.10.3
  - nodebrew use v6.10.3
envs:
  - "# NodeJS"
  - "export NODEBREW_ROOT={{ dir }}"
  - "export PATH=$NODEBREW_ROOT/current/bin:$PATH"
dirs:
  - "{{ dir }}"
