- hosts: all
  remote_user: "{{ user }}"
  vars:
    - user: user
    - user_home: "/home/{{ user }}"
    - workspace: "{{ user_home }}/work"
    - cache: "{{ user_home }}/.tmp"
    - profile: "{{ user_home}}/.bash_profile"
    
  roles:
    - common
    - dotfiles
    - vim
    - linuxbrew
    - nodejs
    - rbenv
    - python
