- name: check node
  shell: "bash -lc 'which node'"
  register: exists
  failed_when: false

- block:
  - include: lib/make-directories.yml
  - include: lib/set-environments.yml
  - include: lib/execute-commands.yml
    args:
      chdir: "{{ nodebrew_root }}"
  when: exists.rc != 0
