- include: lib/git-clone.yml
- include: lib/set-environments.yml

- include: brew-tap.yml
  with_items: "{{ brew_taps }}"

- name: brew install
  shell: "bash -lc 'brew install {{ item }}'"
  with_items: "{{ brew_packages }}"

- name: check libcrypto
  stat:
    path: "{{ dir }}/lib/libcrypto.so.1.0.0"
  register: libcrypto

- name: remove openssl
  shell: "bash -lc 'brew uninstall --ignore-dependencies openssl'"
  when: libcrypto.stat.exists

