dir: "{{ cache }}/dotfiles"

remote_repos:
  - repo: https://github.com/kunst1080/dotfiles.git
    dest: "{{ dir }}"
commands:
  - "{{ dir }}/links.sh"
envs:
  - export GOPATH=~/work/go
dirs:
  - "{{ user_home }}/.vim/undo"
  - "{{ user_home }}/.vim/tmp"
