dir: "{{ cache }}/linuxbrew"

remote_repos:
  - repo: https://github.com/Linuxbrew/brew.git
    dest: "{{ dir }}"
envs:
  - "# Linuxbrew"
  - "export PATH={{ dir }}/bin:$PATH"
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - export LD_LIBRARY_PATH="$(brew --prefix)/lib:$LD_LIBRARY_PATH"

brew_taps:
  - sachaos/todoist
brew_packages:
  - zsh
  - tmux
  - go
  - bc
  - tig
  - nkf
  - jq
  - moreutils
  - num-utils
  - patchutils
  - colordiff
  - mecab
  - mecab-ipadic
  - jdk
  - sbt
  - icu4c
  - peco
  - hugo
  - pwgen
  - todoist
