remote:
  repo: https://github.com/Linuxbrew/brew.git
dir: "{{ cache }}/linuxbrew"
brew: "{{ dir }}/bin/brew"
taps:
  - sachaos/todoist
packages:
  - zsh
  - tmux
  - go
  - bc
  - tig
  - nkf
  - jq
  - moreutils
  - num-utils
  - patchutils
  - colordiff
  - mecab
  - mecab-ipadic
  - jdk
  - sbt
  - icu4c
  - peco
  - hugo
  - pwgen
  - todoist
envs:
  - "export PATH={{ dir }}/bin:$PATH"
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - export LD_LIBRARY_PATH="$(brew --prefix)/lib:$LD_LIBRARY_PATH"
