remote:
  repo: https://github.com/Shougo/dein.vim.git
  installer: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh

dir: "{{ cache }}/vim"
repo: "{{ dir }}/dein.vim"
installer: "{{ dir }}/dein-installer.sh"
