- name: check dein
  stat:
    path: "{{ dir }}/dein.vim"
  register: dein

- block:
  - include: lib/make-directories.yml
  - include: lib/git-clone.yml
  - include: lib/get-url.yml
  - include: lib/execute-commands.yml
  when: not dein.stat.exists

